# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import spartanmessenger_pb2 as spartanmessenger__pb2


class MessageServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MessageStream = channel.unary_stream(
        '/grpc.MessageServer/MessageStream',
        request_serializer=spartanmessenger__pb2.Empty.SerializeToString,
        response_deserializer=spartanmessenger__pb2.Message.FromString,
        )
    self.SendMessage = channel.unary_unary(
        '/grpc.MessageServer/SendMessage',
        request_serializer=spartanmessenger__pb2.Message.SerializeToString,
        response_deserializer=spartanmessenger__pb2.Empty.FromString,
        )


class MessageServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def MessageStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MessageStream': grpc.unary_stream_rpc_method_handler(
          servicer.MessageStream,
          request_deserializer=spartanmessenger__pb2.Empty.FromString,
          response_serializer=spartanmessenger__pb2.Message.SerializeToString,
      ),
      'SendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=spartanmessenger__pb2.Message.FromString,
          response_serializer=spartanmessenger__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.MessageServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
